const parseWords = (source) => source.trim().split(/\s+/u);

// A compact, curated answer set keeps the demo auditable and dependency-free.
// All entries are five letters in the Turkish alphabet.
export const ANSWERS = parseWords(`
ABECE ACABA ACELE ACEMİ ADRES AHENK AHŞAP AJANS AKICI AKREP
AKŞAM AKTİF AKTÖR ALACA ALAKA ALARM ALBÜM ALÇAK ALENİ ALKIŞ
ALKOL ALMAK ALTIN AMBAR AMELE AMİGO AMPUL ANCAK ANKET ANLAM
ANLIK ANONS ANTEN ANTİK ANTRE ARABA ARACI ARAMA ARIZA ARMUT
ARŞİV ASABİ ASKER ASTIM AŞAMA AŞIRI ATAMA ATLAS AVANS AVİZE
AYDIN AYLAK AYRAN AZAMİ AZLIK BAGAJ BAHAR BAHİS BAKAN BAKIM
BAKIR BAKIŞ BALIK BALON BARAK BARIŞ BASIK BASIN BASİT BASKI
BAVUL BAYAT BAYIR BEBEK BEDEN BEKÇİ BELGE BELKİ BESİN BETON
BEYİN BIÇAK BİBER BİÇİM BİDON BİLEK BİLET BİLGİ BİTKİ BİTİŞ
BOĞAZ BOYUN BOZUK BÖCEK BÖLGE BÖLÜM BRANŞ BUÇUK BUHAR BULUT
BURUN BÜTÜN BÜYÜK CADDE CANLI CEVAP CEVİZ CİHAZ CÜMLE ÇABUK
ÇADIR ÇAĞRI ÇAKIL ÇAMUR ÇANTA ÇARŞI ÇAYIR ÇEKİM ÇELİK ÇEŞİT
ÇEVRE ÇİÇEK ÇİZGİ ÇOCUK ÇORAP ÇÖZÜM DAMAR DAMAT DAVET DAVUL
DEĞER DELİK DEMET DEMİR DENEK DENİZ DERGİ DERİN DETAY DEVRE
DİKEY DİLEK DİNAR DİREK DİŞÇİ DOĞAL DOĞRU DOLAP DOLGU DONÖR
DÖNER DÖNÜŞ DURAK DURUM DUVAR DÜĞME DÜNYA EDEBİ EKRAN EKMEK
EMLAK ENGEL ERKEK ERKEN ESNAF EVCİL EVRAK EYLÜL FAKİR FAZLA
FENER FERAH FİDAN FİKİR FİNAL FİRMA FITIK FORMA FOSİL FIRÇA
GARAJ GELİR GENEL GEREK GİDON GİYİM GİZLİ GÖBEK GÖĞÜS GÖREV
GÖRÜŞ GURUR GÜBRE GÜNEŞ GÜZEL HABER HACİM HAFİF HAFTA HAKEM
HALKA HAMUR HASTA HATIR HAVUÇ HAYAL HAYAT HEDEF HELAL HESAP
HEVES HEYET HIZLI HOROZ HUZUR ISLAK İÇERİ İÇMEK İDARE İFADE
İHALE İHBAR İKAME İKLİM İNSAN İPTAL İRADE İSHAL İSTEK KABAK
KADIN KAHVE KALEM KALIP KANAL KANAT KANUN KAPAK KARIN KARMA
KAŞIK KAYIK KAYIP KAYIT KAZAN KEBAP KEFİR KEMİK KENDİ KESİK
KEŞİF KİBAR KILIF KİLİM KİMYA KİRLİ KİTAP KİTLE KLİMA KOLON
KOMŞU KONAK KONUM KOŞUL KÖMÜR KÖPEK KÖPRÜ KREDİ KULAK KURAL
KURUM KUŞAK KÜÇÜK LAMBA LİMAN LİSTE MADEN MAKAS MAKET MALUM
MARKA MASAJ MEDYA MEKAN MELEK MESAJ METAL METRE MEYVE MODEL
MORAL MOTOR NEDEN NEFES NEHİR NOKTA NOTER NÖBET OPERA ORTAK
ÖDEME ÖNLEM ÖRNEK PAKET PANEL PARÇA PERDE PETEK PİLAV PLAZA
POLİS POMPA POSTA PROJE RADAR RAKAM RAPOR RESİM ROBOT ROMAN
SABAH SABİT SABIR SAÇMA SAHİP SAKİN SALON SANAT SAVAŞ SEBEP
SEBZE SEDYE SEÇİM SEÇME SEHPA SERİN SESLİ ŞEHİR ŞEKER ŞEKİL
ŞİFRE ŞİMDİ ŞOFÖR TABAK TABLO TALEP TARAF TARİF TARİH TATİL
TAVUK TEKER TEMEL TEMAS TEMİZ TERİM TERZİ TESİS TIBBİ TOHUM
TOKAT TOPUK TÖREN UYGUN UZMAN ÜCRET VAGON VALİZ VATAN VİDEO
VİRÜS YAĞIŞ YAKIN YALAN YANIT YARIN YATAK YAVAŞ YAZAR YEMEK
YERLİ YEŞİL YILAN YOĞUN YÜREK ZAMAN ZARAR ZEMİN ZİHİN
`);

// Extra accepted guesses are deliberately separate from the answer pool.
export const EXTRA_GUESSES = parseWords(`
BENİM SENİN BİZİM SİZİN BUNUN ŞUNUN KİMİN NEYİN BUNLA ŞUNLA
SENCE SİZCE GELDİ GİTTİ YAPTI BAKTI KALDI BULDU VERDİ GÖRDÜ
DÖNDÜ SORDU DURDU KOŞTU KAÇTI TUTTU KAPTI SUSTU GÜLDÜ YAZDI
ÇİZDİ SİLDİ BİTTİ ÇIKTI GİRDİ DOĞDU YATTI DÜŞTÜ YÜZDÜ GEÇTİ
SEÇTİ KIRDI KESTİ DELDİ SERDİ GERDİ BASTI SARDI VURDU KURDU
BOZDU ÇÖZDÜ DOLDU SOLDU DONDU YANDI SÖNDÜ PİŞTİ TAŞTI ŞAŞTI
COŞTU KOPTU ALDIM ALDIN ALDIK OLDUM OLDUN OLDUK İÇTİM YEDİM
DEDİM DEDİN DEDİK İNDİM UÇTUM ÖLDÜM ATTIM ÖPTÜM İTTİM YAPAR
BAKAR KALAR SORAR DURUR KOŞAR KAÇAR TUTAR ÇİZER SİLER BİTER
ÇIKAR GİRER DÜŞER GEÇER SEÇER KIRAR KESER DELER SERER GERER
BASAR SARAR VURUR KURAR BOZAR ÇÖZER SOLAR DONAR YANAR SÖNER
PİŞER TAŞAR ŞAŞAR COŞAR KOPAR SATAR EVLER EVDEN EVİNE ELLER
İŞLER AYLAR ERLER OTLAR ATLAR ADLAR AVLAR İLLER SULAR KÖYDE
KÖYÜN KÖYÜM SUYUN SUYUM SUDAN SUYLA YOLDA YOLUM YOLUN DOSTA
DOSTU MASAM MASAN AKLIM AKLIN FİKRİ ŞEHRİ RENGİ VAKTİ HACMİ
BURNU BOYNU KARNI GÖĞSÜ YÜZÜM YÜZÜN GÖZÜM GÖZÜN SÖZÜM SÖZÜN
SESİM SESİN DİLİM DİLİN DIŞIM OKULA OKULU ADAMI ANNEM ANNEN
BABAM BABAN ABLAM ABLAN OĞLUM OĞLUN KIZIM KIZIN ADINI YERİM
YERİN YERDE ELDEN ELİNE ELİNİ İŞİNE İŞİNİ İÇİNE İÇİNİ DIŞTA
DIŞIN ÜSTTE ÜSTÜM ALTTA ÖNÜNE ÖNÜNÜ ARKAN ARKAM YANIM YANIN
GELEN GİDEN YAPAN BAKAN KALAN BULAN VEREN GÖREN DÖNEN SORAN
DURAN KOŞAN KAÇAN TUTAN KAPAN SUSAN GÜLEN YAZAN ÇİZEN SİLEN
BİTEN ÇIKAN GİREN YATAN DÜŞEN YÜZEN GEÇEN SEÇEN KIRAN KESEN
DELEN SEREN GEREN BASAN SARAN VURAN KURAN BOZAN ÇÖZEN DOLAN
SOLAN DONAN YANAN SÖNEN PİŞEN TAŞAN ŞAŞAN COŞAN KOPAN SATAN
GİDİN YAPIN BAKIN KALIN BULUN VERİN GÖRÜN DÖNÜN SORUN DURUN
KOŞUN KAÇIN TUTUN KAPIN SUSUN GÜLÜN YAZIN ÇİZİN SİLİN BİTİN
ÇIKIN GİRİN YATIN DÜŞÜN GEÇİN SEÇİN KIRIN KESİN DELİN GERİN
SARIN VURUN KURUN BOZUN ÇÖZÜN DOLUN SOLUN DONUN SÖNÜN PİŞİN
ŞAŞIN COŞUN KOPUN SATIN EMOJİ VİRAL SİBER MODEM LİDAR KODLU
ADMİN KANKA SELAM TAMAM FİBER MOBİL BLOĞU LİNKİ LİNKE MAİLİ MAİLE
`);

export const ALLOWED_WORDS = [...new Set([...ANSWERS, ...EXTRA_GUESSES])];
